In [33]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import log_loss
from sklearn.metrics import classification_report
# path_tr='../Dataset/data/data_apicall/train.csv'
# path_futr='../Dataset/data/data_apicall/train_full.csv'
# path_te='../Dataset/data/data_apicall/test.csv'
# path_val='../Dataset/data/data_apicall/val.csv'

path_tr='../Dataset/data/data_section/normal_train.csv'
path_futr='../Dataset/data/data_section/normal_trainfull.csv'
path_te='../Dataset/data/data_section/normal_test.csv'
path_val='../Dataset/data/data_section/normal_val.csv'
top_feature=150

In [34]:
train = np.genfromtxt(path_tr, delimiter=",", dtype=str)
val = np.genfromtxt(path_val, delimiter=",", dtype=str)

In [35]:
x_data  = train[1:,0:top_feature]
x_label = train[1:,-1]
x_data=x_data.astype(np.float)
x_label=x_label.astype(np.int)
# Binarize the output
x_label = label_binarize(x_label, classes=[1,2,3,4,5,6,7,8,9])

y_data  = val[1:,0:top_feature]
y_data=y_data.astype(np.float)
y_label = val[1:,-1]
y_label=y_label.astype(np.int)
woby=y_label
# Binarize the output
y_label = label_binarize(y_label, classes=[1,2,3,4,5,6,7,8,9])

In [36]:
c=[0.01,0.1,1,10,100]
g=[0.01,0.1,1,10,100]
loss=100
opt_c=0
opt_g=0
for i in c:
    for j in g:    
        clf = OneVsRestClassifier(svm.SVC(kernel='rbf',C=i,gamma=j, probability=True))
        clf_f = clf.fit(x_data, x_label)
        y_score=clf_f.decision_function(y_data)
        y_predict_prob=clf_f.predict_proba(y_data)
        y_predict=clf_f.predict(y_data)
        pre=y_predict.argmax(1)
        pre=pre+1
        a=log_loss(y_label,y_predict_prob)
        if a<loss:
            opt_c=i
            opt_g=j
            loss=a
       # print(confusion_matrix(woby,pre))
        print('log loss: ',a,'  C: ',i,'  G: ',j)

log loss:  1.9665844935026837   C:  0.01   G:  0.01
log loss:  1.2867714015557499   C:  0.01   G:  0.1
log loss:  1.020537684733057   C:  0.01   G:  1
log loss:  1.0131420005272735   C:  0.01   G:  10
log loss:  0.7461457975037877   C:  0.01   G:  100
log loss:  1.2067153792555352   C:  0.1   G:  0.01
log loss:  0.9966226878308355   C:  0.1   G:  0.1
log loss:  1.000689421352957   C:  0.1   G:  1
log loss:  0.8833576296352129   C:  0.1   G:  10
log loss:  0.6775332490271362   C:  0.1   G:  100
log loss:  1.0202955250223913   C:  1   G:  0.01
log loss:  1.001880467084202   C:  1   G:  0.1
log loss:  0.9612409332361376   C:  1   G:  1
log loss:  0.6780740344677404   C:  1   G:  10
log loss:  0.5480405306399186   C:  1   G:  100
log loss:  0.9973142232655378   C:  10   G:  0.01
log loss:  0.9812423591912823   C:  10   G:  0.1
log loss:  0.8594850354638509   C:  10   G:  1
log loss:  0.5904814153602944   C:  10   G:  10
log loss:  0.44822472402503816   C:  10   G:  100
log loss:  0.9830679

In [43]:
train = np.genfromtxt(path_futr, delimiter=",", dtype=str)
test = np.genfromtxt(path_te, delimiter=",", dtype=str)

In [44]:
y_score=clf_f.decision_function(y_data)
y_predict_prob=clf_f.predict_proba(y_data)
y_predict=clf_f.predict(y_data)
pre=y_predict.argmax(1)
pre=pre+1

a=log_loss(y_label,y_predict_prob)

print(confusion_matrix(woby,pre)) 

print('log loss: ',a,'  C: ',opt_c,'  G: ',opt_g)

[[272   0  12   0   0   1   0   1   1]
 [  1 463   0   0   0   0   0   0   0]
 [  1   0 550   0   0   0   0   0   0]
 [  4   0   0  84   0   1   0   0   0]
 [  7   0   0   0   0   0   0   0   0]
 [  4   0   0   2   0 134   0   0   0]
 [  1   0  57   1   0   0  15   0   0]
 [ 57   0   9   1   0   0   0 161   1]
 [ 43   0   0   0   0   0   0   0 146]]
log loss:  0.3219202208938518   C:  100   G:  100


In [45]:
print(classification_report(y_label, y_predict))

              precision    recall  f1-score   support

           0       0.93      0.84      0.88       287
           1       1.00      1.00      1.00       464
           2       0.88      1.00      0.93       551
           3       0.95      0.94      0.95        89
           4       0.00      0.00      0.00         7
           5       0.98      0.97      0.97       140
           6       0.94      0.22      0.35        74
           7       0.99      0.71      0.83       229
           8       0.98      0.77      0.86       189

   micro avg       0.94      0.89      0.91      2030
   macro avg       0.85      0.72      0.75      2030
weighted avg       0.94      0.89      0.90      2030
 samples avg       0.88      0.89      0.88      2030



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [46]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_label, y_predict))

0.8812807881773399
