In [13]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import label_binarize
from mlxtend.feature_selection import SequentialFeatureSelector
import numpy as np


In [14]:
path_tr='../Dataset/data/train_full.csv'
path_te='../Dataset/data/test.csv'

In [15]:
train = np.genfromtxt(path_tr,delimiter=',', dtype=str)
test = np.genfromtxt(path_te, delimiter=',', dtype=str)

In [23]:
x_data = train[1:, 0:-2]
x_label = train[1:, -1]
x_data = x_data.astype(np.float)
x_label = x_label.astype(np.int)
x_label = label_binarize(x_label, classes=[1,2,3,4,5,6,7,8,9])

y_data = test[1:, 0:-2]
y_data = y_data.astype(np.float)
y_label = test[1:, -1]
y_label = label_binarize(y_label, classes=[1,2,3,4,5,6,7,8,9])

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [25]:
print(train[1:, -1])
print(x_label)
print(x_data)

['1' '1' '1' ... '9' '9' '9']
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]
[[0.10734463 0.03631266 0.00210264 ... 0.         0.         0.        ]
 [0.10734463 0.12117969 0.00417533 ... 0.         0.         0.        ]
 [0.10734463 0.13996139 0.00298323 ... 0.         0.         0.        ]
 ...
 [0.10169492 0.00679247 0.00215655 ... 0.         0.         0.        ]
 [0.10169492 0.01614956 0.00149761 ... 0.         0.         0.        ]
 [0.10169492 0.03292743 0.00693691 ... 0.         0.         0.        ]]


In [26]:
feature_selector_fw = SequentialFeatureSelector(RandomForestClassifier(n_jobs=-1),
           k_features=500,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=2)

In [29]:
print(x_label)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [27]:
features = feature_selector_fw.fit(x_data, x_label)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

In [ ]:
filtered_features= train_features.columns[list(features.k_feature_idx_)]
filtered_features

In [ ]:
clf = RandomForestClassifier(n_estimators=100, random_state=41, max_depth=3)
clf.fit(train_features[filtered_features].fillna(0), train_labels)

train_pred = clf.predict_proba(train_features[filtered_features].fillna(0))
print('Accuracy on training set: {}'.format(roc_auc_score(train_labels, train_pred[:,1])))

test_pred = clf.predict_proba(test_features[filtered_features].fillna(0))
print('Accuracy on test set: {}'.format(roc_auc_score(test_labels, test_pred [:,1])))